import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card';
import SelectVariants from '../components/SelectVariants';
import Header from '../components/Header';

import * as React from 'react';


export default function Home() {
  const [age, setAge] = React.useState('');

  const handleChange = (event) => {
    setAge(event.target.value);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <SelectVariants />
      
      <Card />


    </div>
  )
}
