import Head from 'next/head'
import Card from '../components/Card';
import SelectVariants from '../components/SelectVariants';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import * as React from 'react';
import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';


export default function Home() {
  const [age, setAge] = React.useState('');

  const handleChange = (event) => {
    setAge(event.target.value);
  };
  return (
    <div>
      <Head>
        <title>Cube | Ressources relationnelles </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box 
      sx={{ marginLeft: '13.9vw', backgroundColor: '#FBFBFB'}}
      >
      <Header />
      <Sidebar />
      <br />
      <br />
      <br />
      <br />
      <br />
      <TextField
        hiddenLabel
        id="filled-hidden-label-normal"
        defaultValue="Normal"
        variant="filled"
      />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <SelectVariants />
      <Card />
      </Box>
    </div>
  )
}
